spring.application.name=share-resume

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB}

spring.flyway.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB}
spring.flyway.user=${DB_USER}
spring.flyway.password=${DB_PASSWORD}

jwt.private.key=${JWT_PRIVATE_KEY}
jwt.public.key=${JWT_PUBLIC_KEY}
jwt.expiration.minutes=${JWT_EXPIRATION_MINUTES}
jwt.refresh.token.expiration.days=${JWT_REFRESH_TOKEN_EXPIRATION_DAYS}